apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-generator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-app
  template:
    metadata:
      labels:
        app: resume-app
    spec:
      containers: 
        - name: email-node
          image: twdearth/resume-builder:2
          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: mail-cred
                  key: USER
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: mail-cred
                  key: PASS